version: '3.4'

services:
  
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine  
    
  discountdb:
    image: postgres
    
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce
    
  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: Services/Catalog/CatalogService.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.APi/Dockerfile

volumes:
  mongo_data:  
  portainer_data:   
  postgres_data: 
  pgadmin_data:  




